TABLE=$(read -p "Table: "; echo $REPLY)
OLD_COLUMN=$(read -p "Old Column: "; echo $REPLY)
NEW_COLUMN=$(read -p "New Column: "; echo $REPLY)

sqlite3 "${@:-1}" << EOF
PRAGMA FOREIGN_KEYS=OFF;
BEGIN TRANSACTION;

CREATE TEMPORARY TABLE "_$TABLE" AS SELECT "$OLD_COLUMN" FROM "$TABLE";

ALTER TABLE "$TABLE" DROP "$OLD_COLUMN";
ALTER TABLE "$TABLE" ADD "$NEW_COLUMN" TEXT NULL;

UPDATE "$TABLE" SET "$NEW_COLUMN" = (SELECT "$OLD_COLUMN" FROM "_$TABLE");

COMMIT;
EOF
